name: Schedule Empty Commit

on:
  schedule:
    - cron: '*/5 * * * *' # Runs the job every 5 minutes

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        run: |
          git clone https://github.com/nikAcharya1/streamlit-ML-Nikesh.git
          cd streamlit-ML-Nikesh
          git commit --allow-empty -m "Scheduled empty commit"
          git push origin master
        env:
          GITHUB_TOKEN: ${{ secrets.EC_TOKEN }}
